// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBncmD1r6SpEw04TB48J_juq-Kxfh-o3KE',
    appId: '1:1054531892898:web:66015e54037578647749fb',
    messagingSenderId: '1054531892898',
    projectId: 'mashadali-58162',
    authDomain: 'mashadali-58162.firebaseapp.com',
    storageBucket: 'mashadali-58162.firebasestorage.app',
    measurementId: 'G-C2T68EZ3KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb1X_LtlRtZWpcbQfXxrt_pRRNmWYM0cM',
    appId: '1:1054531892898:android:bc9df315f66725bf7749fb',
    messagingSenderId: '1054531892898',
    projectId: 'mashadali-58162',
    storageBucket: 'mashadali-58162.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcM0179EyYvbqGDHA3Ja3G1nq8KNmXDl8',
    appId: '1:1054531892898:ios:f01a6ff6b103ba5a7749fb',
    messagingSenderId: '1054531892898',
    projectId: 'mashadali-58162',
    storageBucket: 'mashadali-58162.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );
}
